# Generated by Django 3.2.25 on 2025-12-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='founditem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('found_place', models.CharField(max_length=200)),
                ('found_date', models.DateField()),
                ('finder_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='lostitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('lost_place', models.CharField(max_length=200)),
                ('lost_date', models.DateField()),
                ('owner_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
    ]
