# Generated by Django 3.2.25 on 2025-12-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='found_items/'),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='lost_items/'),
        ),
    ]
